name: Prepared SDK env

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  empty:
    runs-on: self-hosted
    steps:
      - name: empty
        run: echo 'Nothing to see here'